-- 코드를 작성해주세요
SELECT SUM(G.SCORE) AS "SCORE",G.EMP_NO,E.EMP_NAME,E.POSITION,E.EMAIL
FROM HR_DEPARTMENT D
JOIN HR_EMPLOYEES E
ON  D.DEPT_ID = E.DEPT_ID
JOIN HR_GRADE G
ON G.EMP_NO = E.EMP_NO
GROUP BY G.EMP_NO
ORDER BY SUM(G.SCORE) DESC
LIMIT 1;